// state for editing task to show/hide update component
export const SELECTING_TASK_REQUESTED = 'SELECTING_TASK_REQUESTED';
export const SELECTING_TASK_SUCCESS = 'SELECTING_TASK_SUCCESS';
export const SELECTING_TASK_FAILED = 'SELECTING_TASK_FAILED';

export const UNSELECTING_TASK_REQUESTED = 'UNSELECTING_TASK_REQUESTED';
export const UNSELECTING_TASK_SUCCESS = 'UNSELECTING_TASK_SUCCESS';
export const UNSELECTING_TASK_FAILED = 'UNSELECTING_TASK_FAILED';

export const CREATE_TASK_REQUESTED = 'CREATE_TASK_REQUESTED';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED';

export const RETRIEVE_TASK_REQUESTED = 'RETRIEVE_TASK_REQUESTED';
export const RETRIEVE_TASK_SUCCESS = 'RETRIEVE_TASK_SUCCESS';
export const RETRIEVE_TASK_FAILED = 'RETRIEVE_TASK_FAILED';

export const UPDATE_TASK_REQUESTED = 'UPDATE_TASK_REQUESTED';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

export const DELETE_TASK_REQUESTED = 'DELETE_TASK_REQUESTED';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';
